### PR TITLE
Update Graphql-js to 0.8.1 (fixes test)

### PR DESCRIPTION
**Pull request by Tallyb**
TODO:

- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by helfer** [comment]
@Tallyb thanks, can you add a line to the changelog as well?

**Comment by DxCx** [comment]
IMO there will be issues with the graphql Typings as facebook did some renames which needs to be renamed in typings first..

from what i noticed:
GraphQLResult => ExecutionResult
Document => DocumentNode

**Comment by DxCx** [comment]
And ofcourse rename them in the code as well...

**Comment by Tallyb** [comment]
@helfer  I did not see  previous upgrades in the chnagelog. Should I still add it?

**Comment by DxCx** [comment]
Note that meanwhile lee released another version (0.8.2)

**Comment by helfer** [comment]
@DxCx that shouldn't be a problem, since it's covered by the current version range.

**Pull request merged**
