### PR TITLE
chore(package): update graphiql version from 0.7.1 to 0.8.0

### PR DESCRIPTION
**Pull request by DxCx**
TODO:
- [x] Update CHANGELOG.md with your change (include reference to issue & this PR)
- [X] Make sure all of the significant new logic is covered by tests
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by DxCx** [comment]
@stubailo / @helfer are we planing on using lerna changelog? or should i update the changelog manually?

**Comment by helfer** [comment]
@DxCx let's do it manually for now.

**Comment by helfer** [comment]
@DxCx when you get a chance, please update the changelog!

**Comment by DxCx** [comment]
@helfer so we are ready,
meanwhile version 0.8.0 was released so i've updated to it instead.
please ACK and we can merge.. :)

**Comment by DxCx** [comment]
@helfer / @stubailo let's merge?

**Comment by helfer** [comment]
@DxCx Thanks, merged!

**Pull request merged**
