### PR TITLE
Changed Typings to @types/graphql (WIP)

### PR DESCRIPTION
**Pull request by DxCx**
Also, had to align to latest graphql version (0.8.2).

### CODE REVIEW

**Comment by DxCx** [comment]
I'm stuck in a module resultion issue which i don't have much time to get into,
if someone can help that can accelerate this PR..
Basiclly, because of the lerna's linking, it looks like typescript will include typings from node_module/@types of depended packages.
this leads to duplicate identifier on graphql:
```
                                                                                                                                                                                    [364/97369]
2239     export { BreakingChange } from 'graphql/utilities/findBreakingChanges';
                  ~~~~~~~~~~~~~~

../graphql-server-module-operation-store/node_modules/@types/graphql/index.d.ts(2239,14): error TS2300: Duplicate identifier 'BreakingChange'.


2387     export const BreakingChangeType: {
                      ~~~~~~~~~~~~~~~~~~

../graphql-server-module-operation-store/node_modules/@types/graphql/index.d.ts(2387,18): error TS2451: Cannot redeclare block-scoped variable 'BreakingChangeType'.


2396     type BreakingChangeKey = 'FIELD_CHANGED_KIND'
              ~~~~~~~~~~~~~~~~~

../graphql-server-module-operation-store/node_modules/@types/graphql/index.d.ts(2396,10): error TS2300: Duplicate identifier 'BreakingChangeKey'.


2403     export type BreakingChange = {
                     ~~~~~~~~~~~~~~

../graphql-server-module-operation-store/node_modules/@types/graphql/index.d.ts(2403,17): error TS2300: Duplicate identifier 'BreakingChange'.


2574     const introspectionQuery: string;
               ~~~~~~~~~~~~~~~~~~

../graphql-server-module-operation-store/node_modules/@types/graphql/index.d.ts(2574,11): error TS2451: Cannot redeclare block-scoped variable 'introspectionQuery'.


2589     type IntrospectionType =
              ~~~~~~~~~~~~~~~~~

../graphql-server-module-operation-store/node_modules/@types/graphql/index.d.ts(2589,10): error TS2300: Duplicate identifier 'IntrospectionType'.


2640     type IntrospectionTypeRef =
              ~~~~~~~~~~~~~~~~~~~~

../graphql-server-module-operation-store/node_modules/@types/graphql/index.d.ts(2640,10): error TS2300: Duplicate identifier 'IntrospectionTypeRef'.


2814     class TypeInfo {
               ~~~~~~~~

../graphql-server-module-operation-store/node_modules/@types/graphql/index.d.ts(2814,11): error TS2300: Duplicate identifier 'TypeInfo'.

```

**Comment by helfer** [comment]
@DxCx could we solve this by updating all dependent packages that we have control over?

**Comment by DxCx** [comment]
We can align typed-graphql to @types and then it might work because graphql typings won't be on @types directory.
but it looks like @types/graphql is the one to be maintained for the long run.

@Urigo , @davidyaha do you have any insights on this issue before i'm going to deep dive into it?
looks like @types/graphql is being imported from siblings packages as well for some odd reason.

**Comment by helfer** [comment]
Closing this in favor of #260. Sorry we didn't see this PR @DxCx 😞

**Pull request closed without merging**
