### PR TITLE
chore(misc): add Node 7 to Travis CI

### PR DESCRIPTION
**Pull request by DxCx**

### CODE REVIEW

**Comment by stubailo** [comment]
Hmmm... in theory, we should only need to run the fibers tests on node 4, because that's what Meteor uses.

**Comment by DxCx** [comment]
Yeah but can you configure travis for that?

I didnt have time to dig deeper but looks like it wont be installed on node 7 (failed to compile)
On my local linux ive installed node 7 and fibers and it worked well..

**Comment by helfer** [comment]
@DxCx Isn't the issue with the failing tests that we configured travis not to allow sudo?

**Comment by DxCx** [comment]
well, fibers is the one to break, i've opened this laverdet/node-fibers#331 issue..

**Comment by DxCx** [comment]
will apply as part of tweaks since i have it working on top of them already.

**Pull request closed without merging**
